// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.SwitchService.proto

package com.zhangwuji.im.protobuf;

public final class IMSwitchService {
  private IMSwitchService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IMP2PCmdMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.SwitchService.IMP2PCmdMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *cmd id:		0x0601
     * </pre>
     *
     * <code>required uint32 from_user_id = 1;</code>
     */
    boolean hasFromUserId();
    /**
     * <pre>
     *cmd id:		0x0601
     * </pre>
     *
     * <code>required uint32 from_user_id = 1;</code>
     */
    int getFromUserId();

    /**
     * <code>required uint32 to_user_id = 2;</code>
     */
    boolean hasToUserId();
    /**
     * <code>required uint32 to_user_id = 2;</code>
     */
    int getToUserId();

    /**
     * <code>required string cmd_msg_data = 3;</code>
     */
    boolean hasCmdMsgData();
    /**
     * <code>required string cmd_msg_data = 3;</code>
     */
    java.lang.String getCmdMsgData();
    /**
     * <code>required string cmd_msg_data = 3;</code>
     */
    com.google.protobuf.ByteString
        getCmdMsgDataBytes();
  }
  /**
   * Protobuf type {@code IM.SwitchService.IMP2PCmdMsg}
   */
  public  static final class IMP2PCmdMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:IM.SwitchService.IMP2PCmdMsg)
      IMP2PCmdMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IMP2PCmdMsg.newBuilder() to construct.
    private IMP2PCmdMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IMP2PCmdMsg() {
      fromUserId_ = 0;
      toUserId_ = 0;
      cmdMsgData_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IMP2PCmdMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              fromUserId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              toUserId_ = input.readUInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              cmdMsgData_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhangwuji.im.protobuf.IMSwitchService.internal_static_IM_SwitchService_IMP2PCmdMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhangwuji.im.protobuf.IMSwitchService.internal_static_IM_SwitchService_IMP2PCmdMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg.class, com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg.Builder.class);
    }

    private int bitField0_;
    public static final int FROM_USER_ID_FIELD_NUMBER = 1;
    private int fromUserId_;
    /**
     * <pre>
     *cmd id:		0x0601
     * </pre>
     *
     * <code>required uint32 from_user_id = 1;</code>
     */
    public boolean hasFromUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *cmd id:		0x0601
     * </pre>
     *
     * <code>required uint32 from_user_id = 1;</code>
     */
    public int getFromUserId() {
      return fromUserId_;
    }

    public static final int TO_USER_ID_FIELD_NUMBER = 2;
    private int toUserId_;
    /**
     * <code>required uint32 to_user_id = 2;</code>
     */
    public boolean hasToUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 to_user_id = 2;</code>
     */
    public int getToUserId() {
      return toUserId_;
    }

    public static final int CMD_MSG_DATA_FIELD_NUMBER = 3;
    private volatile java.lang.Object cmdMsgData_;
    /**
     * <code>required string cmd_msg_data = 3;</code>
     */
    public boolean hasCmdMsgData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string cmd_msg_data = 3;</code>
     */
    public java.lang.String getCmdMsgData() {
      java.lang.Object ref = cmdMsgData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cmdMsgData_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string cmd_msg_data = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCmdMsgDataBytes() {
      java.lang.Object ref = cmdMsgData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmdMsgData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFromUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCmdMsgData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, fromUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, toUserId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cmdMsgData_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, fromUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, toUserId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cmdMsgData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg)) {
        return super.equals(obj);
      }
      com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg other = (com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg) obj;

      boolean result = true;
      result = result && (hasFromUserId() == other.hasFromUserId());
      if (hasFromUserId()) {
        result = result && (getFromUserId()
            == other.getFromUserId());
      }
      result = result && (hasToUserId() == other.hasToUserId());
      if (hasToUserId()) {
        result = result && (getToUserId()
            == other.getToUserId());
      }
      result = result && (hasCmdMsgData() == other.hasCmdMsgData());
      if (hasCmdMsgData()) {
        result = result && getCmdMsgData()
            .equals(other.getCmdMsgData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFromUserId()) {
        hash = (37 * hash) + FROM_USER_ID_FIELD_NUMBER;
        hash = (53 * hash) + getFromUserId();
      }
      if (hasToUserId()) {
        hash = (37 * hash) + TO_USER_ID_FIELD_NUMBER;
        hash = (53 * hash) + getToUserId();
      }
      if (hasCmdMsgData()) {
        hash = (37 * hash) + CMD_MSG_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getCmdMsgData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IM.SwitchService.IMP2PCmdMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IM.SwitchService.IMP2PCmdMsg)
        com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhangwuji.im.protobuf.IMSwitchService.internal_static_IM_SwitchService_IMP2PCmdMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhangwuji.im.protobuf.IMSwitchService.internal_static_IM_SwitchService_IMP2PCmdMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg.class, com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg.Builder.class);
      }

      // Construct using com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fromUserId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        toUserId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        cmdMsgData_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhangwuji.im.protobuf.IMSwitchService.internal_static_IM_SwitchService_IMP2PCmdMsg_descriptor;
      }

      @java.lang.Override
      public com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg getDefaultInstanceForType() {
        return com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg build() {
        com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg buildPartial() {
        com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg result = new com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fromUserId_ = fromUserId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.toUserId_ = toUserId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cmdMsgData_ = cmdMsgData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg) {
          return mergeFrom((com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg other) {
        if (other == com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg.getDefaultInstance()) return this;
        if (other.hasFromUserId()) {
          setFromUserId(other.getFromUserId());
        }
        if (other.hasToUserId()) {
          setToUserId(other.getToUserId());
        }
        if (other.hasCmdMsgData()) {
          bitField0_ |= 0x00000004;
          cmdMsgData_ = other.cmdMsgData_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasFromUserId()) {
          return false;
        }
        if (!hasToUserId()) {
          return false;
        }
        if (!hasCmdMsgData()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int fromUserId_ ;
      /**
       * <pre>
       *cmd id:		0x0601
       * </pre>
       *
       * <code>required uint32 from_user_id = 1;</code>
       */
      public boolean hasFromUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *cmd id:		0x0601
       * </pre>
       *
       * <code>required uint32 from_user_id = 1;</code>
       */
      public int getFromUserId() {
        return fromUserId_;
      }
      /**
       * <pre>
       *cmd id:		0x0601
       * </pre>
       *
       * <code>required uint32 from_user_id = 1;</code>
       */
      public Builder setFromUserId(int value) {
        bitField0_ |= 0x00000001;
        fromUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *cmd id:		0x0601
       * </pre>
       *
       * <code>required uint32 from_user_id = 1;</code>
       */
      public Builder clearFromUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fromUserId_ = 0;
        onChanged();
        return this;
      }

      private int toUserId_ ;
      /**
       * <code>required uint32 to_user_id = 2;</code>
       */
      public boolean hasToUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 to_user_id = 2;</code>
       */
      public int getToUserId() {
        return toUserId_;
      }
      /**
       * <code>required uint32 to_user_id = 2;</code>
       */
      public Builder setToUserId(int value) {
        bitField0_ |= 0x00000002;
        toUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 to_user_id = 2;</code>
       */
      public Builder clearToUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        toUserId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object cmdMsgData_ = "";
      /**
       * <code>required string cmd_msg_data = 3;</code>
       */
      public boolean hasCmdMsgData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string cmd_msg_data = 3;</code>
       */
      public java.lang.String getCmdMsgData() {
        java.lang.Object ref = cmdMsgData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cmdMsgData_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string cmd_msg_data = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCmdMsgDataBytes() {
        java.lang.Object ref = cmdMsgData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmdMsgData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string cmd_msg_data = 3;</code>
       */
      public Builder setCmdMsgData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        cmdMsgData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string cmd_msg_data = 3;</code>
       */
      public Builder clearCmdMsgData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cmdMsgData_ = getDefaultInstance().getCmdMsgData();
        onChanged();
        return this;
      }
      /**
       * <code>required string cmd_msg_data = 3;</code>
       */
      public Builder setCmdMsgDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        cmdMsgData_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:IM.SwitchService.IMP2PCmdMsg)
    }

    // @@protoc_insertion_point(class_scope:IM.SwitchService.IMP2PCmdMsg)
    private static final com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg();
    }

    public static com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<IMP2PCmdMsg>
        PARSER = new com.google.protobuf.AbstractParser<IMP2PCmdMsg>() {
      @java.lang.Override
      public IMP2PCmdMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMP2PCmdMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IMP2PCmdMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IMP2PCmdMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zhangwuji.im.protobuf.IMSwitchService.IMP2PCmdMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IM_SwitchService_IMP2PCmdMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IM_SwitchService_IMP2PCmdMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026IM.SwitchService.proto\022\020IM.SwitchServi" +
      "ce\"M\n\013IMP2PCmdMsg\022\024\n\014from_user_id\030\001 \002(\r\022" +
      "\022\n\nto_user_id\030\002 \002(\r\022\024\n\014cmd_msg_data\030\003 \002(" +
      "\tB\035\n\031com.zhangwuji.im.protobufH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_IM_SwitchService_IMP2PCmdMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IM_SwitchService_IMP2PCmdMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IM_SwitchService_IMP2PCmdMsg_descriptor,
        new java.lang.String[] { "FromUserId", "ToUserId", "CmdMsgData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
